[package]
name = "crypto"
version = "0.1.0"
authors = ["hideki1217 <okumurahidekikangeki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

math_utils={path="../math_utils"}
num="0.4"
array-macro="2.1"


